---
# Component with both GitHub and Jira Scorecards
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdh
  annotations:
    github.com/project-slug: redhat-developer/rhdh
    backstage.io/source-location: url:https://github.com/redhat-developer/rhdh
    jira/project-key: RHDHBUGS
spec:
  type: service
  owner: janus-authors
  lifecycle: production
