apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-janus
  title: Backstage Janus
  description: |
    This is the Janus Community Showcase of Backstage.io
  links:
    - title: Janus Website
      url: https://janus-idp.io
    - title: Janus Showcase
      url: https://showcase.janus-idp.io/
    - title: Blog
      url: https://janus-idp.io/blog
    - title: Backstage Discord
      url: https://discord.com/servers/backstage-687207715902193673
  annotations:
    argocd/app-name: "janus-idp"
    backstage.io/kubernetes-id: "developer-hub"
    github.com/project-slug: redhat-developer/rhdh
    quay.io/repository-slug: rhdh-community/rhdh
    backstage.io/techdocs-ref: url:https://github.com/redhat-developer/rhdh
    backstage.io/kubernetes-namespace: myapps
    sonarqube.org/project-key: janus-idp_backstage-janus
spec:
  type: website
  system: janus-idp
  owner: janus-authors
  lifecycle: production
  dependsOn:
    - resource:pgdb
    - resource:argocd
    - resource:obc
    - resource:keycloak
    - resource:github
