apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  namespace: development
  name: guests
spec:
  type: team
  children: [user:development/guest]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: development
  name: guest
  title: John Smith
spec:
  memberOf:
    - group:development/guests
