apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: default
  name: dzemanov
spec:
  memberOf:
    - janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: janus-authors
spec:
  type: team
  children: []
