apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
spec:
  type: team
  children: [team-b]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-b
spec:
  type: team
  children: [team-c]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-c
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: default
  name: dzemanov
spec:
  memberOf:
    - team-a
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: default
  name: u1
spec:
  memberOf:
    - team-b
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: default
  name: u2
spec:
  memberOf:
    - team-c
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  namespace: default
  name: u3
spec:
  memberOf:
    - team-a
